title: Lucas Soares # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ML engineer and professionally curious
  <br><br>
  Trying really hard to write good code. 
  <br><br>
  <a href="https://www.linkedin.com/in/lucas-soares-969044167/">LinkedIn</a> 
  <br><br>
  <a href="https://github.com/EnkrateiaLucca">github</a> 
  <br><br>
  <a href="https://twitter.com/LucasEnkrateia2">twitter</a> 
  <br><br>
  <a href="https://lucas-soares.medium.com">medium</a> 
  
theme: jekyll-theme-minimal
